FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma
RUN npm ci

COPY tsconfig.json ./
COPY src ./src

RUN npm run prisma:generate && npm run build && npm prune --omit=dev

EXPOSE 3000

CMD ["npm", "start"]
